name: "dependabot jira ticket sync"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  dependabot-scan:
    name: Scan for issues
    uses: Kno2/action-workflows/.github/workflows/push-alerts-to-jira-ubuntu.yml@master
    with:
      jira_project_key: DEP
    secrets: inherit
